import ScrollSuave from './modules/scrollSuave.js';
import initAnimateScroll from './modules/animate-scroll.js';
import initAccordion from './modules/accordion.js';
import initTabnav from './modules/tabnav.js';
import initModal from './modules/modal.js';
import initTooltip from './modules/tooltip.js';
import initMenuDropdown from './modules/menu-dropdown.js';
import initMenuMobile from './modules/menu-mobile.js';
import initFuncionamento from './modules/funcionamento.js';
import initFetchAnimais from './modules/fetch-animais.js';
import initFetchBitcoin from './modules/fetch-bitcoin.js';

const scrollSuave = new ScrollSuave('[data-menu="list"] a[href^="#"]');
scrollSuave.init();
initAnimateScroll();
initAccordion();
initTabnav();
initModal();
initTooltip();
initMenuDropdown();
initMenuMobile();
initFetchAnimais();
initFuncionamento();
initFetchBitcoin();
